### ISSUE TITLE
کلاس ششم!

### ISSUE THREAD

**Issue by Paptoos** [AshkanLaei/web-school#1]
من می تونم برای کلاس پنجم رو انجام بدم !

**Comment by AshkanLaei** [comment]
ای بابا بزار بسازم پروژه رو! چرا اینقدر زود میپری وسط کار! یه لحظه فکر کردم گیت‌هاب باگ داره

**Comment by Paptoos** [comment]
باشه ، مشکلی نداره ،

**Comment by AshkanLaei** [comment]
<div dir=rtl>خب حالا میتونی شروع کنی!</div>

**Comment by Paptoos** [comment]
شروع کردم فارسی پنجم رو

**Comment by AshkanLaei** [comment]
تا کجا پیش رفتی؟

**Comment by Paptoos** [comment]
دارم متن ها رو می نویسم ، یک قالب هم از قبل دارم فقط باید سر همش کنم ، عکس و صوت دانلودش راحته

**Comment by AshkanLaei** [comment]
نه فعلاً رو قالب کار نکنیم بهتره متن ها رو زود تر بنویس که پروژه شروع بشه

**Comment by Paptoos** [comment]
باشه

**Comment by Paptoos** [comment]
الان تقربا فایل متنی دو درس اول آماده است ، پول ریگوئست بدم یا همه رو تموم کنم ؟

**Comment by AshkanLaei** [comment]
پول‌ریکوئست بده فعلاً تا اینجاش اضافه بشه
