### ISSUE TITLE
سوال ؟

### ISSUE THREAD

**Issue by Paptoos** [AshkanLaei/web-school#3]
(نامعلوم) یعنی چی ؟
بعد بخوان و بیاندیش ها یا بخوان و حفظ کن ها رو چه شماره ای بزنم

**Comment by AshkanLaei** [comment]
نامعلوم یعنی این شماره ها برای درس های این دوره ها نیستن دوره دوم متوسطه باشن فکر کنم شایدم من اشتباه میکنم ولی توی ابتدایی و متوسطه اول ندیدم این کد ها رو

اونا رو با شماره درس قبلی بزن یه خط تیره و یک هم بزن بعدش.
اگه دو سه تا بودن هم جای یک بنویس دو و سه فقط ترتیب اشتباه نشه

**Comment by Paptoos** [comment]
باشه ، امروز یا فردا دو درس دوم هم آماده می شه
