### ISSUE TITLE
تبدیل pdf  به txt

### ISSUE THREAD

**Issue by Paptoos** [AshkanLaei/web-school#4]
سلام
این مقاله رو بخونید :
[virgool](https://virgool.io/@mrashidi/persian-ocr-made-easy-aulili3tlhqa)
خیلی دقیق تشخیص می ده ، بعدش هم باید فقط با کپی پیست بگذاریم توی مارک داون
با یک کمی ویراستاری
تستش کردم ، توی یک صفحه فقط دو کلمه اشتباه داشت

**Comment by AshkanLaei** [comment]
سلام
خیلی خوب به نظر میاد
میتونی چند صفحه رو امتحان کنی؟
فقط باید با فونت های سخت هم انجام بده
مثلا فارسی بعضی قسمت هاش با فونت نستعلیق یا شبیه به اونه

**Comment by AshkanLaei** [comment]
من خودم گوگل درایو ندارم به خاطر همین گفتم

**Comment by Paptoos** [comment]
با نستعلیق فارسی امتحان کردم ، ولی ریاضی فکر نکنم مناسب باشه 
چون کسر و اعداد فارسی سخته

**Comment by AshkanLaei** [comment]
اشکال نداره هر جا سخت بود دستی انجام میدیم
فقط کسی نمیشناسی کمک کنه تو پروژه؟

**Comment by Paptoos** [comment]
سعی ام رو می کنم چند نفر دیگه رو هم بیارم ، یک ذره جلو بریم فقط از یک ایده خارج بشه و شروع کنیم به اجرا کردنش ، افراد بیشتری کمک می کنند
