### ISSUE TITLE
استفاده از فرمت docx

### ISSUE THREAD

**Issue by mehanalavimajd** [AshkanLaei/web-school#6]
سلام ، می خواستم بهتون یک نکته ای رو بگم که اکثر کاربرای معمولی از ویندوز استفاده می کنن و معمولا روی هر ویندوزی یه نسخه ی آفیسی هست به همین دلیل به نظرم بهتره فایل ها رو با فرمت docx هم در کنار صفحات وب و حالا pdf ذخیره کنیم

**Comment by Paptoos** [comment]
سلام
من کرده بودم
ولی ابن کلا پروژه وب هست و قرار نیست یک پروژه دسکتاپ باشه
( البته وقتی تموم شد برای نسخه دسکتاپ هم شاید ساختیم)

**Comment by mehanalavimajd** [comment]
بله خیلی هم خوب می شه که نسخه ی دسکتاپ داشته باشه . اگه بخواید من می تونم بیام توی پروژه (مخصوصا توی قسمت وبش که خیلی خوب میشه)

**Comment by Paptoos** [comment]
این یک پروژه متن باز هست و هر کسی می تواند وارد شد 😄

**Comment by AshkanLaei** [comment]
<div dir=rtl>

سلام.

منم خوشحال می‌شم کمک کنی :smile: 

راستش نیازی به فرمت‌های دیگه نیست چون هدف اینه که تو نرم‌افزاری که از طرف خودمون منتشر می‌شه مشاهده کنن پس نیازی به پشتیبانی از طرف برنامه‌های دیگه نیست :rocket: 

</div>

**Comment by mehanalavimajd** [comment]
Ok . پس باشه
